apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../picture
patchStrategicMerge:
  - picture-deployment.yaml
  - picture-service.yaml 
  - picture-route.yaml 
  - picture-destination-rule.yaml 
