apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../picture
commonLabels: 
  app: picture
  version: v1
nameSuffix: -v2
patchesStrategicMerge:
  - picture-deployment.yaml

