apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture
  labels:
    app: picture-v2
spec:
  selector:
    matchLabels:
      app: picture-v2
  template:
    metadata:
      labels:
        app: picture-v2
    spec:
      containers:
      - name: picture-v2
        image: gcr.io/picture-generator/picture-service:1.0.6 
        env:
        - name: DB_URL
          value: mongodb://picture:picturepw@mongodb-picture:27017/pictures
        - name: PROJECT_ID
          value: picture-generator
        ports:
        - containerPort: 3334
      serviceAccountName: k8s-pubsub
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
