apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture-v2
spec:
  template:
    spec:
      containers:
      - name: picture
        image: gcr.io/picture-generator/picture-service:1.0.6 
        env:
        - name: DB_URL
          value: mongodb://picture:picturepw@mongodb-picture:27017/pictures
        - name: PROJECT_ID
          value: picture-generator
        ports:
        - containerPort: 3334
