apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture
  namespace: default
  labels:
    app: picture
    version: v1
spec:
  selector:
    matchLabels:
      app: picture
      version: v1
  template:
    metadata:
      labels:
        app: picture
        version: v1
    spec:
      containers:
      - name: picture
        image: gcr.io/picture-generator/picture-service:1.0.5
        env:
        - name: DB_URL
          value: mongodb://picture:picturepw@mongodb-picture:27017/pictures
        - name: PROJECT_ID
          value: picture-generator
        ports:
        - containerPort: 3334
      serviceAccountName: k8s-pubsub
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
