apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  releaseName: istio-ingressgateway
  interval: 1m
  chart: 
    spec: 
      chart: ./manifests/charts/gateway
      sourceRef:
        kind: GitRepository
        name: istio
