apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 1m
  url: https://github.com/istio/istio
  ref:
    branch: master
