apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-git-repository.yaml
  - mongo-helm-release.yaml
  - image-automation.yaml
  - ./policy
  - ./registry
  - ./mouse-events
  - ./picture
  - ./istio
  - ./istio-ingress
