apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bitnami 
  namespace: default 
spec:
  interval: 1m
  url: https://github.com/bitnami/charts
  ref:
    branch: master
