apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mongo
  namespace: default 
spec:
  interval: 1m
  url: https://github.com/bitnami/charts/bitname/mongodb
  ref:
    branch: master
