apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mongo
  namespace: default
spec:
  interval: 1m0s
  url: https://kubernetes-charts.storage.googleapis.com/mongodb
  secretRef:
    name: regcred
