apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-picture
  namespace: default 
spec:
  releaseName: mongodb-picture
  interval: 1m
  chart: 
    spec: 
      chart: ./bitnami/mongodb
      sourceRef:
        kind: GitRepository
        name: bitnami 
  values:
    auth:
      enabled: true
      rootPassword: "root"
      rootUser: "root"
      # usernames: 
      #   - picture
      # passwords: 
      #   - picturepw
      # databases:
      #   - pictures
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
