apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default 
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: mongodb
  interval: 1m
  chart: 
    spec: 
      chart: mongo
      version: 13.1.2
      sourceRef:
        kind: GitRepository
        name: mongo 
        namespace: default
  values:
    # image:
    #   repository: bitnami/mongodb
    #   tag: 5.0.12
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
