apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mongo
  namespace: default
spec:
  interval: 5m0s
  url: kubernetes-charts.storage.googleapis.com/bitnami/mongodb
  type: "oci"
  # secretRef:
  #   name: regcred
