apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mouse-events
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mouse-events
  policy:
    semver:
      range: '>= 1.0.0'
