apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture
  namespace: default
  labels:
    app: picture
spec:
  selector:
    matchLabels:
      app: picture
  template:
    metadata:
      labels:
        app: picture
    spec:
      containers:
      - name: picture
        image: gcr.io/picture-generator/picture-service:1.0.4 # {"$imagepolicy": "flux-system:picture"}
        env:
        - name: DB_URL
          value: mongodb://mongodb-picture:27017/pictures
        - name: PROJECT_ID
          value: picture-generator
      serviceAccountName: k8s-pubsub 
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
