apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: picture
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - picture-gateway
  http:
  - match:
    - uri:
        prefix: /api/pictures
    route:
    - destination:
        port:
          number: 3334
        host: picture
